-d C:\Users\imaoca09\OneDrive\source\tangnano\neuro9k\impl\gwsynthesis\neuro9k.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\imaoca09\OneDrive\source\tangnano\neuro9k\src\neuro9k.cst
-cfg C:\Users\imaoca09\OneDrive\source\tangnano\neuro9k\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
